version: '3'

# Highlight.io services for Coolify deployment
services:
  # Infrastructure services
  clickhouse:
    image: ${CLICKHOUSE_IMAGE_NAME:-clickhouse/clickhouse-server:24.3.15.72-alpine}
    restart: on-failure
    expose:
      - 9000
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - TZ=${TZ:-America/Los_Angeles}
      - SERVICE_PASSWORD_CLICKHOUSE=${SERVICE_PASSWORD_CLICKHOUSE:-password}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-default}
      - CLICKHOUSE_USERNAME=${CLICKHOUSE_USERNAME:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}

  zookeeper:
    image: ${ZOOKEEPER_IMAGE_NAME:-confluentinc/cp-zookeeper:7.7.0}
    restart: on-failure
    expose:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - TZ=${TZ:-America/Los_Angeles}
    healthcheck:
      test: ["CMD", "bash", "-c", "echo stat | nc localhost 2181"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}

  kafka:
    image: ${KAFKA_IMAGE_NAME:-confluentinc/cp-kafka:7.7.0}
    restart: on-failure
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://kafka:9092}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TOPIC=${KAFKA_TOPIC:-dev}
      - TZ=${TZ:-America/Los_Angeles}
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}

  postgres:
    image: ${POSTGRES_IMAGE_NAME:-ankane/pgvector:v0.5.1}
    restart: on-failure
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD:-postgres}
      - POSTGRES_USER=${PSQL_USER:-postgres}
      - POSTGRES_DB=${PSQL_DB:-postgres}
      - TZ=${TZ:-America/Los_Angeles}
      - SERVICE_PASSWORD_DB=${SERVICE_PASSWORD_DB:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}

  redis:
    image: ${REDIS_IMAGE_NAME:-redis:7.4.0}
    restart: on-failure
    expose:
      - 6379
    volumes:
      - redis-data:/data
    environment:
      - TZ=${TZ:-America/Los_Angeles}
      - SERVICE_PASSWORD_REDIS=${SERVICE_PASSWORD_REDIS:-password}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}

  collector:
    image: ${OTEL_COLLECTOR_IMAGE_NAME:-otel/opentelemetry-collector-contrib:0.120.0}
    restart: on-failure
    expose:
      - 4318
    environment:
      - TZ=${TZ:-America/Los_Angeles}
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - collector-config:/etc/otel
      - type: bind
        source: ./otel-config.yaml
        target: /etc/otel/config.yaml
        content: |
          receivers:
            otlp:
              protocols:
                http:
                  endpoint: 0.0.0.0:4318
                  cors:
                    allowed_origins:
                      - https://${SERVICE_FQDN_FRONTEND}
                      - http://${SERVICE_FQDN_FRONTEND}
                      - https://${REACT_APP_FRONTEND_URI:-localhost:3000}
                      - http://${REACT_APP_FRONTEND_URI:-localhost:3000}
                      - "*"
          processors:
            batch:
              timeout: 1s
          exporters:
            logging:
              loglevel: debug
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [logging]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4318/"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}
      - traefik.enable=true
      - traefik.http.routers.collector.rule=Host(`collector.${REACT_APP_FRONTEND_URI:-localhost:3000}`)
      - traefik.http.routers.collector.entrypoints=http
      - traefik.http.routers.collector-secure.rule=Host(`collector.${REACT_APP_FRONTEND_URI:-localhost:3000}`)
      - traefik.http.routers.collector-secure.entrypoints=https
      - traefik.http.routers.collector-secure.tls=true
      - traefik.http.routers.collector-secure.tls.certresolver=letsencrypt
      - traefik.http.services.collector.loadbalancer.server.port=4318

  predictions:
    build:
      context: .
      dockerfile: ./packages/predictions/predictions.Dockerfile
    restart: on-failure
    expose:
      - 5001
    environment:
      - TZ=${TZ:-America/Los_Angeles}
      - SERVICE_FQDN_PREDICTIONS=${SERVICE_FQDN_PREDICTIONS:-predictions.localhost:3000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - highlight-network
    labels:
      - coolify.managed=true
      - coolify.type=service
      - coolify.applicationId=${COOLIFY_APP_ID:-1}
      - traefik.enable=true
      - traefik.http.routers.predictions.rule=Host(`${SERVICE_FQDN_PREDICTIONS:-predictions.localhost:3000}`)
      - traefik.http.routers.predictions.entrypoints=http
      - traefik.http.services.predictions.loadbalancer.server.port=5001
      
  # Application services
  backend:
    image: ${BACKEND_IMAGE_NAME:-ghcr.io/highlight/highlight-backend:docker-v0.5.2}
    restart: on-failure
    expose:
      - 8082
    volumes:
      - highlight-data:/highlight-data
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${PSQL_USER:-postgres}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD:-postgres}
      - POSTGRES_DB=${PSQL_DB:-postgres}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - COLLECTOR_ENDPOINT=http://collector:4318
      - PREDICTIONS_ENDPOINT=http://predictions:5001
      - SERVICE_FQDN_BACKEND=/private,/public,/health
      - SERVICE_PASSWORD_BACKEND=${SERVICE_PASSWORD_BACKEND:-password}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS:-password}
      - DB_PASSWORD=${SERVICE_PASSWORD_DB:-postgres}
      - DISABLE_CORS=${DISABLE_CORS:-true}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - SSL=${SSL:-false}
      - ENV=${ENVIRONMENT:-production}
      - ON_PREM=true
      - OBJECT_STORAGE_FS=${OBJECT_STORAGE_FS:-/highlight-data}
      - EMAIL_OPT_OUT_SALT=${EMAIL_OPT_OUT_SALT:-salt}
      - REACT_APP_AUTH_MODE=${REACT_APP_AUTH_MODE:-password}
      - SESSION_FILE_PATH_PREFIX=${SESSION_FILE_PATH_PREFIX:-/tmp/}
    depends_on:
      clickhouse:
        condition: service_healthy
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      collector:
        condition: service_healthy
      predictions:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/health"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - coolify.managed=true
      - coolify.type=application
      - coolify.applicationId=${COOLIFY_APP_ID:-1}
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.backend.rule=Host(`${REACT_APP_FRONTEND_URI:-localhost:3000}`) && PathPrefix(`/private`, `/public`, `/health`)
      - traefik.http.routers.backend.entrypoints=http
      - traefik.http.routers.backend-secure.rule=Host(`${REACT_APP_FRONTEND_URI:-localhost:3000}`) && PathPrefix(`/private`, `/public`, `/health`)
      - traefik.http.routers.backend-secure.entrypoints=https
      - traefik.http.routers.backend-secure.tls=true
      - traefik.http.routers.backend-secure.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8082
    networks:
      - highlight-network

  frontend:
    image: ${FRONTEND_IMAGE_NAME:-ghcr.io/highlight/highlight-frontend:docker-v0.5.2}
    restart: on-failure
    expose:
      - 3000
      - 6006
      - 8080
    env_file: .env
    environment:
      - SERVICE_FQDN_FRONTEND=${SERVICE_FQDN_FRONTEND:-localhost:3000}
      - REACT_APP_FRONTEND_URI=${REACT_APP_FRONTEND_URI:-localhost:3000}
      - REACT_APP_PRIVATE_GRAPH_URI=https://${REACT_APP_FRONTEND_URI:-localhost:3000}/private
      - REACT_APP_PUBLIC_GRAPH_URI=https://${REACT_APP_FRONTEND_URI:-localhost:3000}/public
      - REACT_APP_OTLP_ENDPOINT=https://collector.${REACT_APP_FRONTEND_URI:-localhost:3000}
      - BACKEND_URL=https://${REACT_APP_FRONTEND_URI:-localhost:3000}
      - AUTH_SECRET=${SERVICE_PASSWORD_AUTH:-password}
      - REACT_APP_AUTH_MODE=${REACT_APP_AUTH_MODE:-password}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - DISABLE_CORS=${DISABLE_CORS:-true}
      - SSL=${SSL:-false}
      - REACT_APP_IN_DOCKER=${REACT_APP_IN_DOCKER:-true}
      - REACT_APP_DISABLE_ANALYTICS=${REACT_APP_DISABLE_ANALYTICS:-false}
      - REACT_APP_FRONTEND_ORG=${REACT_APP_FRONTEND_ORG:-1}
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - coolify.managed=true
      - coolify.type=application
      - coolify.applicationId=${COOLIFY_APP_ID:-1}
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.frontend.rule=Host(`${REACT_APP_FRONTEND_URI:-localhost:3000}`)
      - traefik.http.routers.frontend.entrypoints=http
      - traefik.http.routers.frontend-secure.rule=Host(`${REACT_APP_FRONTEND_URI:-localhost:3000}`)
      - traefik.http.routers.frontend-secure.entrypoints=https
      - traefik.http.routers.frontend-secure.tls=true
      - traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - highlight-network

volumes:
  highlight-data:
  clickhouse-data:
  postgres-data:
  redis-data:
  collector-config:

networks:
  highlight-network:
    driver: bridge
    external: ${USE_EXTERNAL_NETWORK:-true}
    name: ${NETWORK_NAME:-highlight-network}
    labels:
      - coolify.managed=true
