version: '3'

# Highlight.io services for Coolify deployment
services:
  # Infrastructure services
  clickhouse:
    image: ${CLICKHOUSE_IMAGE_NAME}
    restart: on-failure
    expose:
      - 9000
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - TZ=${TZ}
    networks:
      - highlight-network

  zookeeper:
    image: ${ZOOKEEPER_IMAGE_NAME}
    restart: on-failure
    expose:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - TZ=${TZ}
    networks:
      - highlight-network

  kafka:
    image: ${KAFKA_IMAGE_NAME}
    restart: on-failure
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS:-PLAINTEXT://kafka:9092}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - TZ=${TZ}
    depends_on:
      - zookeeper
    networks:
      - highlight-network

  postgres:
    image: ${POSTGRES_IMAGE_NAME}
    restart: on-failure
    expose:
      - 5432
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD:-postgres}
      - POSTGRES_USER=${PSQL_USER:-postgres}
      - POSTGRES_DB=${PSQL_DB:-postgres}
      - TZ=${TZ}
    networks:
      - highlight-network

  redis:
    image: ${REDIS_IMAGE_NAME}
    restart: on-failure
    expose:
      - 6379
    volumes:
      - redis-data:/data
    environment:
      - TZ=${TZ}
    networks:
      - highlight-network

  collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    restart: on-failure
    expose:
      - 4318
    environment:
      - TZ=${TZ}
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - collector-config:/etc/otel
      - type: bind
        source: ./otel-config.yaml
        target: /etc/otel/config.yaml
        content: |
          receivers:
            otlp:
              protocols:
                http:
                  endpoint: 0.0.0.0:4318
          processors:
            batch:
              timeout: 1s
          exporters:
            logging:
              loglevel: debug
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [logging]
    networks:
      - highlight-network

  predictions:
    build:
      context: .
      dockerfile: ./packages/predictions/predictions.Dockerfile
    restart: on-failure
    expose:
      - 5001
    environment:
      - TZ=${TZ}
    networks:
      - highlight-network
      
  # Application services
  backend:
    image: ${BACKEND_IMAGE_NAME}
    restart: on-failure
    expose:
      - 8082
    volumes:
      - highlight-data:/highlight-data
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${PSQL_USER:-postgres}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD:-postgres}
      - POSTGRES_DB=${PSQL_DB:-postgres}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - COLLECTOR_ENDPOINT=http://collector:4318
      - PREDICTIONS_ENDPOINT=http://predictions:5001
      - SERVICE_FQDN_BACKEND=/private,/public,/health
    depends_on:
      - clickhouse
      - kafka
      - postgres
      - redis
      - collector
      - predictions
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.backend.rule=Host(`${REACT_APP_FRONTEND_URI}`) && PathPrefix(`/private`, `/public`, `/health`)
      - traefik.http.routers.backend.entrypoints=http
      - traefik.http.routers.backend-secure.rule=Host(`${REACT_APP_FRONTEND_URI}`) && PathPrefix(`/private`, `/public`, `/health`)
      - traefik.http.routers.backend-secure.entrypoints=https
      - traefik.http.routers.backend-secure.tls=true
      - traefik.http.routers.backend-secure.tls.certresolver=letsencrypt
      - traefik.http.services.backend.loadbalancer.server.port=8082
    networks:
      - highlight-network

  frontend:
    image: ${FRONTEND_IMAGE_NAME}
    restart: on-failure
    expose:
      - 3000
      - 6006
      - 8080
    env_file: .env
    environment:
      - SERVICE_FQDN_FRONTEND
      - REACT_APP_PRIVATE_GRAPH_URI=http://backend:8082/private
      - REACT_APP_PUBLIC_GRAPH_URI=http://backend:8082/public
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.frontend.rule=Host(`${REACT_APP_FRONTEND_URI}`)
      - traefik.http.routers.frontend.entrypoints=http
      - traefik.http.routers.frontend-secure.rule=Host(`${REACT_APP_FRONTEND_URI}`)
      - traefik.http.routers.frontend-secure.entrypoints=https
      - traefik.http.routers.frontend-secure.tls=true
      - traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000
    networks:
      - highlight-network

volumes:
  highlight-data:
  clickhouse-data:
  postgres-data:
  redis-data:
  collector-config:

networks:
  highlight-network:
    driver: bridge
