# documentation: https://highlightio.com/docs
# slogan: Highlight Hobby Edition - Monitor and Debug your applications
# tags: monitoring,debugging,observability,highlight
# logo: https://raw.githubusercontent.com/highlight/highlight/main/design/logo/logo.svg
# port: 8080

version: "3.8"

services:
  frontend:
    image: ghcr.io/highlight/highlight-frontend:docker-v0.5.2
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_HIGHLIGHT_FRONTEND_8080
      - REACT_APP_BACKEND_URI=${SERVICE_URL_HIGHLIGHT_BACKEND}
      - REACT_APP_FRONTEND_URI=${SERVICE_URL_HIGHLIGHT_FRONTEND}
      - HOST=0.0.0.0
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_HIGHLIGHT}
    ports:
      - "8080:8080"
      - "3000:3000"
      - "6006:6006"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.highlight-frontend.rule=Host(`${COOLIFY_PUBLIC_HOSTNAME}`)"
      - traefik.http.routers.highlight-frontend.entryPoints=http
      - traefik.http.services.highlight-frontend.loadbalancer.server.port=8080
    depends_on:
      - backend
    networks:
      - highlight-network

  backend:
    image: ghcr.io/highlight/highlight-backend:docker-v0.5.2
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_HIGHLIGHT_BACKEND_8082=/api
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_HIGHLIGHT}
      - REACT_APP_FRONTEND_URI=${SERVICE_URL_HIGHLIGHT_FRONTEND}
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
    ports:
      - "8082:8082"
    volumes:
      - highlight-data:/highlight-data
    labels:
      - traefik.enable=true
      - "traefik.http.routers.highlight-backend.rule=Host(`${COOLIFY_PUBLIC_HOSTNAME}`) && PathPrefix(`/api`)"
      - traefik.http.routers.highlight-backend.entryPoints=http
      - traefik.http.services.highlight-backend.loadbalancer.server.port=8082
    depends_on:
      - postgres
      - redis
      - kafka
      - clickhouse
      - zookeeper
      - collector
    networks:
      - highlight-network

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_DB=highlightio
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - highlight-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass "${SERVICE_PASSWORD_REDIS}"
    volumes:
      - redis-data:/data
    networks:
      - highlight-network

  zookeeper:
    image: bitnami/zookeeper:3.8
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper
    networks:
      - highlight-network

  kafka:
    image: bitnami/kafka:3.4
    restart: unless-stopped
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - highlight-network

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=highlightio
      - CLICKHOUSE_USER=${SERVICE_USER_CLICKHOUSE:-default}
      - CLICKHOUSE_PASSWORD=${SERVICE_PASSWORD_CLICKHOUSE}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - highlight-network

  collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    restart: unless-stopped
    depends_on:
      - kafka
      - clickhouse
    networks:
      - highlight-network
    volumes:
      - ./collector.yml:/etc/otel-collector-config.yaml:ro
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - OTLP_ENDPOINT=${SERVICE_URL_HIGHLIGHT_BACKEND}/otel
    ports:
      - "4317:4317"
      - "4318:4318"

networks:
  highlight-network:
    driver: bridge

volumes:
  highlight-data:
  postgres-data:
  redis-data:
  zookeeper-data:
  kafka-data:
  clickhouse-data:
