# documentation: https://highlightio.com/docs
# slogan: Highlight Hobby Edition - Monitor and Debug your applications
# tags: monitoring,debugging,observability,highlight
# logo: https://raw.githubusercontent.com/highlight/highlight/main/design/logo/logo.svg
# port: 3000

version: "3.8"

services:
  frontend:
    image: ghcr.io/highlight/highlight-frontend:docker-v0.5.2
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URI=http://backend:8082
      - REACT_APP_FRONTEND_URI=http://localhost:3000
    ports:
      - "3000:8080"
    depends_on:
      - backend

  backend:
    image: ghcr.io/highlight/highlight-backend:docker-v0.5.2
    restart: unless-stopped
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
    volumes:
      - highlight-data:/highlight-data
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
      - clickhouse
      - collector

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-highlightio}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis-data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=highlightio
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    restart: unless-stopped
    volumes:
      - ./collector.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - OTLP_ENDPOINT=http://backend:8082/otel
    ports:
      - "4317:4317"
      - "4318:4318"

volumes:
  highlight-data:
  postgres-data:
  redis-data:
  clickhouse-data:
