# documentation: https://www.highlight.io/docs/general/company/open-source/hosting/self-host-hobby
# slogan: Open source Screenrecording and Headmap Analytics
# tags: Screenrecording, Headmap Analytics, Open Source
# logo: svgs/highlight.png
# port: 3000

services:
  # Startup the infra
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.15.72-alpine
    restart: on-failure
    expose:
      - 9000
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    restart: on-failure
    expose:
      - 2181

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    restart: on-failure
    depends_on:
      - zookeeper
    expose:
      - 9092

  postgres:
    image: ankane/pgvector:v0.5.1
    restart: on-failure
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    restart: on-failure
    expose:
      - 6379
    volumes:
      - redis-data:/data

  collector:
    image: atilladeniz1/highlight-collector:latest
    restart: on-failure
    expose:
      - 4318

  predictions:
    image: atilladeniz1/highlight-predictions:latest
    restart: on-failure
    depends_on:
      - clickhouse
      - kafka
      - postgres

  backend:
    image: ghcr.io/highlight/highlight-backend:docker-v0.5.2
    restart: on-failure
    depends_on:
      - clickhouse
      - kafka
      - postgres
      - redis
      - collector
    ports:
      - "8082:8082"

  frontend:
    image: ghcr.io/highlight/highlight-frontend:docker-v0.5.2
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  clickhouse-data:
  postgres-data:
  redis-data: